# language: haskell

env:
 - GHCVER=8.0.2
 - GHCVER=8.2.2
 - GHCVER=8.4.4
 - GHCVER=8.6.5
 - GHCVER=8.8.3
 - GHCVER=8.10.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-3.2 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-3.2 update

script:
 - cabal-3.2 configure --enable-tests
 - cabal-3.2 build
 - cabal-3.2 test --test-show-details=streaming -j1
 - cabal-3.2 haddock
 - cabal-3.2 sdist


